language: node_js
env:
  global:
    - GH_REF: github.com/w3c/apa.git
    
git:
  depth: 3
  
branches:
  only:
    master

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
  - sh -e /etc/init.d/xvfb start

install:
  - cd ../..
  - npm install respec

before_script:
  - git config --global user.email "cooper@w3.org"
  - git config --global user.name "michael-n-cooper"
  
script:
  - mkdir gh-pages
  - cd gh-pages
  - git clone --depth=1 --branch=gh-pages https://github.com/w3c/apa.git
  - cd apa
  - cp -R ../../w3c/apa/fast/* fast
  - cp -R ../../w3c/apa/media-accessibility-reqs/* media-accessibility-reqs
  - node ../../node_modules/respec/tools/respec2html.js --src file://`pwd`/../../w3c/apa/fast/index.html --out fast/index.html
  - node ../../node_modules/respec/tools/respec2html.js --src file://`pwd`/../../w3c/apa/payment-accessibility-reqs/index.html --out payment-accessibility-reqs/index.html
  - node ../../node_modules/respec/tools/respec2html.js --src file://`pwd`/../../w3c/apa/media-accessibility-reqs/index.html --out media-accessibility-reqs/index.html

after_success:
  - git add -A .
  - git commit -m "Generated by TRAVIS-CI"
  - git push "https://${GH_TOKEN}@${GH_REF}" gh-pages > /dev/null 2>&1
